#![allow(dead_code)]

pub const MAX_PACKET_ID: u16 = 347;

pub mod ids {
    pub const KEEP_ALIVE: u16 = 0;
    pub const LOGIN: u16 = 1;
    pub const PLAY_STATUS: u16 = 2;
    pub const SERVER_TO_CLIENT_HANDSHAKE: u16 = 3;
    pub const CLIENT_TO_SERVER_HANDSHAKE: u16 = 4;
    pub const DISCONNECT: u16 = 5;
    pub const RESOURCE_PACKS_INFO: u16 = 6;
    pub const RESOURCE_PACK_STACK: u16 = 7;
    pub const RESOURCE_PACK_CLIENT_RESPONSE: u16 = 8;
    pub const TEXT: u16 = 9;
    pub const SET_TIME: u16 = 10;
    pub const START_GAME: u16 = 11;
    pub const ADD_PLAYER: u16 = 12;
    pub const ADD_ACTOR: u16 = 13;
    pub const REMOVE_ACTOR: u16 = 14;
    pub const ADD_ITEM_ACTOR: u16 = 15;
    pub const SERVER_PLAYER_POST_MOVE_POSITION: u16 = 16;
    pub const TAKE_ITEM_ACTOR: u16 = 17;
    pub const MOVE_ABSOLUTE_ACTOR: u16 = 18;
    pub const MOVE_PLAYER: u16 = 19;
    pub const PASSENGER_JUMP_DEPRECATED: u16 = 20;
    pub const UPDATE_BLOCK: u16 = 21;
    pub const ADD_PAINTING: u16 = 22;
    pub const TICK_SYNC_DEPRECATED: u16 = 23;
    pub const LEVEL_SOUND_EVENT_V1_DEPRECATED: u16 = 24;
    pub const LEVEL_EVENT: u16 = 25;
    pub const TILE_EVENT: u16 = 26;
    pub const ACTOR_EVENT: u16 = 27;
    pub const MOB_EFFECT: u16 = 28;
    pub const UPDATE_ATTRIBUTES: u16 = 29;
    pub const INVENTORY_TRANSACTION: u16 = 30;
    pub const PLAYER_EQUIPMENT: u16 = 31;
    pub const MOB_ARMOR_EQUIPMENT: u16 = 32;
    pub const INTERACT: u16 = 33;
    pub const BLOCK_PICK_REQUEST: u16 = 34;
    pub const ACTOR_PICK_REQUEST: u16 = 35;
    pub const PLAYER_ACTION: u16 = 36;
    pub const ACTOR_FALL_DEPRECATED: u16 = 37;
    pub const HURT_ARMOR: u16 = 38;
    pub const SET_ACTOR_DATA: u16 = 39;
    pub const SET_ACTOR_MOTION: u16 = 40;
    pub const SET_ACTOR_LINK: u16 = 41;
    pub const SET_HEALTH: u16 = 42;
    pub const SET_SPAWN_POSITION: u16 = 43;
    pub const ANIMATE: u16 = 44;
    pub const RESPAWN: u16 = 45;
    pub const CONTAINER_OPEN: u16 = 46;
    pub const CONTAINER_CLOSE: u16 = 47;
    pub const PLAYER_HOTBAR: u16 = 48;
    pub const INVENTORY_CONTENT: u16 = 49;
    pub const INVENTORY_SLOT: u16 = 50;
    pub const CONTAINER_SET_DATA: u16 = 51;
    pub const CRAFTING_DATA: u16 = 52;
    pub const CRAFTING_EVENT_DEPRECATED: u16 = 53;
    pub const GUI_DATA_PICK_ITEM: u16 = 54;
    pub const ADVENTURE_SETTINGS_DEPRECATED: u16 = 55;
    pub const BLOCK_ACTOR_DATA: u16 = 56;
    pub const PLAYER_INPUT_DEPRECATED: u16 = 57;
    pub const FULL_CHUNK_DATA: u16 = 58;
    pub const SET_COMMANDS_ENABLED: u16 = 59;
    pub const SET_DIFFICULTY: u16 = 60;
    pub const CHANGE_DIMENSION: u16 = 61;
    pub const SET_PLAYER_GAME_TYPE: u16 = 62;
    pub const PLAYER_LIST: u16 = 63;
    pub const SIMPLE_EVENT: u16 = 64;
    pub const LEGACY_TELEMETRY_EVENT: u16 = 65;
    pub const SPAWN_EXPERIENCE_ORB: u16 = 66;
    pub const MAP_DATA: u16 = 67;
    pub const MAP_INFO_REQUEST: u16 = 68;
    pub const REQUEST_CHUNK_RADIUS: u16 = 69;
    pub const CHUNK_RADIUS_UPDATED: u16 = 70;
    pub const ITEM_FRAME_DROP_ITEM_DEPRECATED: u16 = 71;
    pub const GAME_RULES_CHANGED: u16 = 72;
    pub const CAMERA: u16 = 73;
    pub const BOSS_EVENT: u16 = 74;
    pub const SHOW_CREDITS: u16 = 75;
    pub const AVAILABLE_COMMANDS: u16 = 76;
    pub const COMMAND_REQUEST: u16 = 77;
    pub const COMMAND_BLOCK_UPDATE: u16 = 78;
    pub const COMMAND_OUTPUT: u16 = 79;
    pub const UPDATE_TRADE: u16 = 80;
    pub const UPDATE_EQUIP: u16 = 81;
    pub const RESOURCE_PACK_DATA_INFO: u16 = 82;
    pub const RESOURCE_PACK_CHUNK_DATA: u16 = 83;
    pub const RESOURCE_PACK_CHUNK_REQUEST: u16 = 84;
    pub const TRANSFER: u16 = 85;
    pub const PLAY_SOUND: u16 = 86;
    pub const STOP_SOUND: u16 = 87;
    pub const SET_TITLE: u16 = 88;
    pub const ADD_BEHAVIOR_TREE: u16 = 89;
    pub const STRUCTURE_BLOCK_UPDATE: u16 = 90;
    pub const SHOW_STORE_OFFER: u16 = 91;
    pub const PURCHASE_RECEIPT: u16 = 92;
    pub const PLAYER_SKIN: u16 = 93;
    pub const SUBCLIENT_LOGIN: u16 = 94;
    pub const AUTOMATION_CLIENT_CONNECT: u16 = 95;
    pub const SET_LAST_HURT_BY: u16 = 96;
    pub const BOOK_EDIT: u16 = 97;
    pub const NPC_REQUEST: u16 = 98;
    pub const PHOTO_TRANSFER: u16 = 99;
    pub const SHOW_MODAL_FORM: u16 = 100;
    pub const MODAL_FORM_RESPONSE: u16 = 101;
    pub const SERVER_SETTINGS_REQUEST: u16 = 102;
    pub const SERVER_SETTINGS_RESPONSE: u16 = 103;
    pub const SHOW_PROFILE: u16 = 104;
    pub const SET_DEFAULT_GAME_TYPE: u16 = 105;
    pub const REMOVE_OBJECTIVE: u16 = 106;
    pub const SET_DISPLAY_OBJECTIVE: u16 = 107;
    pub const SET_SCORE: u16 = 108;
    pub const LAB_TABLE: u16 = 109;
    pub const UPDATE_BLOCK_SYNCED: u16 = 110;
    pub const MOVE_DELTA_ACTOR: u16 = 111;
    pub const SET_SCOREBOARD_IDENTITY: u16 = 112;
    pub const SET_LOCAL_PLAYER_AS_INIT: u16 = 113;
    pub const UPDATE_SOFT_ENUM: u16 = 114;
    pub const PING: u16 = 115;
    pub const BLOCK_PALETTE_DEPRECATED: u16 = 116;
    pub const SCRIPT_CUSTOM_EVENT: u16 = 117;
    pub const SPAWN_PARTICLE_EFFECT: u16 = 118;
    pub const AVAILABLE_ACTOR_ID_LIST: u16 = 119;
    pub const LEVEL_SOUND_EVENT_V2_DEPRECATED: u16 = 120;
    pub const NETWORK_CHUNK_PUBLISHER_UPDATE: u16 = 121;
    pub const BIOME_DEFINITION_LIST: u16 = 122;
    pub const LEVEL_SOUND_EVENT: u16 = 123;
    pub const LEVEL_EVENT_GENERIC: u16 = 124;
    pub const LECTERN_UPDATE: u16 = 125;
    pub const VIDEO_STREAM_CONNECT_DEPRECATED: u16 = 126;
    pub const ADD_ENTITY_DEPRECATED: u16 = 127;
    pub const REMOVE_ENTITY_DEPRECATED: u16 = 128;
    pub const CLIENT_CACHE_STATUS: u16 = 129;
    pub const ON_SCREEN_TEXTURE_ANIMATION: u16 = 130;
    pub const MAP_CREATE_LOCKED_COPY: u16 = 131;
    pub const STRUCTURE_TEMPLATE_DATA_EXPORT_REQUEST: u16 = 132;
    pub const STRUCTURE_TEMPLATE_DATA_EXPORT_RESPONSE: u16 = 133;
    pub const UNUSED_PLS_USE_ME: u16 = 134;
    pub const CLIENT_CACHE_BLOB_STATUS: u16 = 135;
    pub const CLIENT_CACHE_MISS_RESPONSE: u16 = 136;
    pub const EDUCATION_SETTINGS: u16 = 137;
    pub const EMOTE: u16 = 138;
    pub const MULTIPLAYER_SETTINGS: u16 = 139;
    pub const SETTINGS_COMMAND: u16 = 140;
    pub const ANVIL_DAMAGE: u16 = 141;
    pub const COMPLETED_USING_ITEM: u16 = 142;
    pub const NETWORK_SETTINGS: u16 = 143;
    pub const PLAYER_AUTH_INPUT: u16 = 144;
    pub const CREATIVE_CONTENT: u16 = 145;
    pub const PLAYER_ENCHANT_OPTIONS: u16 = 146;
    pub const ITEM_STACK_REQUEST: u16 = 147;
    pub const ITEM_STACK_RESPONSE: u16 = 148;
    pub const PLAYER_ARMOR_DAMAGE: u16 = 149;
    pub const CODE_BUILDER: u16 = 150;
    pub const UPDATE_PLAYER_GAME_TYPE: u16 = 151;
    pub const EMOTE_LIST: u16 = 152;
    pub const POSITION_TRACKING_DB_SERVER_BROADCAST: u16 = 153;
    pub const POSITION_TRACKING_DB_CLIENT_REQUEST: u16 = 154;
    pub const DEBUG_INFO: u16 = 155;
    pub const PACKET_VIOLATION_WARNING: u16 = 156;
    pub const MOTION_PREDICTION_HINTS: u16 = 157;
    pub const TRIGGER_ANIMATION: u16 = 158;
    pub const CAMERA_SHAKE: u16 = 159;
    pub const PLAYER_FOG_SETTING: u16 = 160;
    pub const CORRECT_PLAYER_MOVE_PREDICTION: u16 = 161;
    pub const ITEM_REGISTRY: u16 = 162;
    pub const FILTER_TEXT_DEPRECATED: u16 = 163;
    pub const CLIENT_BOUND_DEBUG_RENDERER: u16 = 164;
    pub const SYNC_ACTOR_PROPERTY: u16 = 165;
    pub const ADD_VOLUME_ENTITY: u16 = 166;
    pub const REMOVE_VOLUME_ENTITY: u16 = 167;
    pub const SIMULATION_TYPE: u16 = 168;
    pub const NPC_DIALOGUE: u16 = 169;
    pub const EDU_URI_RESOURCE: u16 = 170;
    pub const CREATE_PHOTO: u16 = 171;
    pub const UPDATE_SUB_CHUNK_BLOCKS: u16 = 172;
    pub const PHOTO_INFO_REQUEST_DEPRECATED: u16 = 173;
    pub const SUB_CHUNK: u16 = 174;
    pub const SUB_CHUNK_REQUEST: u16 = 175;
    pub const PLAYER_START_ITEM_COOLDOWN: u16 = 176;
    pub const SCRIPT_MESSAGE: u16 = 177;
    pub const CODE_BUILDER_SOURCE: u16 = 178;
    pub const TICKING_AREAS_LOAD_STATUS: u16 = 179;
    pub const DIMENSION_DATA: u16 = 180;
    pub const AGENT_ACTION: u16 = 181;
    pub const CHANGE_MOB_PROPERTY: u16 = 182;
    pub const LESSON_PROGRESS: u16 = 183;
    pub const REQUEST_ABILITY: u16 = 184;
    pub const REQUEST_PERMISSIONS: u16 = 185;
    pub const TOAST_REQUEST: u16 = 186;
    pub const UPDATE_ABILITIES: u16 = 187;
    pub const UPDATE_ADVENTURE_SETTINGS: u16 = 188;
    pub const DEATH_INFO: u16 = 189;
    pub const EDITOR_NETWORK: u16 = 190;
    pub const FEATURE_REGISTRY: u16 = 191;
    pub const SERVER_STATS: u16 = 192;
    pub const REQUEST_NETWORK_SETTINGS: u16 = 193;
    pub const GAME_TEST_REQUEST: u16 = 194;
    pub const GAME_TEST_RESULTS: u16 = 195;
    pub const PLAYER_CLIENT_INPUT_PERMISSIONS: u16 = 196;
    pub const CLIENT_CHEAT_ABILITY_DEPRECATED: u16 = 197;
    pub const CAMERA_PRESETS: u16 = 198;
    pub const UNLOCKED_RECIPES: u16 = 199;
    pub const CAMERA_INSTRUCTION: u16 = 300;
    pub const COMPRESSED_BIOME_DEFINITION_LIST_DEPRECATED: u16 = 301;
    pub const TRIM_DATA: u16 = 302;
    pub const OPEN_SIGN: u16 = 303;
    pub const AGENT_ANIMATION: u16 = 304;
    pub const REFRESH_ENTITLEMENTS: u16 = 305;
    pub const PLAYER_TOGGLE_CRAFTER_SLOT_REQUEST: u16 = 306;
    pub const SET_PLAYER_INVENTORY_OPTIONS: u16 = 307;
    pub const SET_HUD: u16 = 308;
    pub const AWARD_ACHIEVEMENT: u16 = 309;
    pub const CLIENTBOUND_CLOSE_SCREEN: u16 = 310;
    pub const CLIENTBOUND_LOADING_SCREEN_DEPRECATED: u16 = 311;
    pub const SERVERBOUND_LOADING_SCREEN: u16 = 312;
    pub const JIGSAW_STRUCTURE_DATA: u16 = 313;
    pub const CURRENT_STRUCTURE_FEATURE: u16 = 314;
    pub const SERVERBOUND_DIAGNOSTICS: u16 = 315;
    pub const CAMERA_AIM_ASSIST: u16 = 316;
    pub const CONTAINER_REGISTRY_CLEANUP: u16 = 317;
    pub const MOVEMENT_EFFECT: u16 = 318;
    pub const SET_MOVEMENT_AUTHORITY_MODE_DEPRECATED: u16 = 319;
    pub const CAMERA_AIM_ASSIST_PRESETS: u16 = 320;
    pub const CLIENT_CAMERA_AIM_ASSIST: u16 = 321;
    pub const CLIENT_MOVEMENT_PREDICTION_SYNC: u16 = 322;
    pub const UPDATE_CLIENT_OPTIONS: u16 = 323;
    pub const PLAYER_VIDEO_CAPTURE: u16 = 324;
    pub const PLAYER_UPDATE_ENTITY_OVERRIDES: u16 = 325;
    pub const PLAYER_LOCATION: u16 = 326;
    pub const CLIENTBOUND_CONTROL_SCHEME_SET: u16 = 327;
    pub const SERVER_SCRIPT_DEBUG_DRAWER: u16 = 328;
    pub const SERVERBOUND_PACK_SETTING_CHANGE: u16 = 329;
    pub const CLIENTBOUND_DATA_STORE: u16 = 330;
    pub const GRAPHICS_PARAMETER_OVERRIDE: u16 = 331;
    pub const SERVERBOUND_DATA_STORE: u16 = 332;
    pub const CLIENTBOUND_DATA_DRIVEN_UI_SHOW_SCREEN: u16 = 333;
    pub const CLIENTBOUND_DATA_DRIVEN_UI_CLOSE_ALL_SCREENS: u16 = 334;
    pub const CLIENTBOUND_DATA_DRIVEN_UI_RELOAD: u16 = 335;
    pub const CLIENTBOUND_TEXTURE_SHIFT: u16 = 336;
    pub const VOXEL_SHAPES: u16 = 337;
    pub const CAMERA_SPLINE: u16 = 338;
    pub const CAMERA_AIM_ASSIST_ACTOR_PRIORITY: u16 = 339;
    pub const RESOURCE_PACKS_READY_FOR_VALIDATION: u16 = 340;
    pub const LOCATOR_BAR: u16 = 341;
    pub const PARTY_CHANGED: u16 = 342;
    pub const SERVERBOUND_DATA_DRIVEN_SCREEN_CLOSED: u16 = 343;
    pub const SYNC_WORLD_CLOCKS: u16 = 344;
    pub const CLIENTBOUND_ATTRIBUTE_LAYER_SYNC: u16 = 345;
    pub const SERVER_STORE_INFO: u16 = 346;
    pub const SERVER_PRESENCE_INFO: u16 = 347;
    pub const PARTY_DESTINATION_COOKIE_RESPONSE: u16 = 350;}

pub use ids::*;

pub fn label(packet_id: u16) -> String {
    let name = match packet_id {
        ids::LOGIN => "Login",
        ids::PLAY_STATUS => "PlayStatus",
        ids::DISCONNECT => "Disconnect",
        ids::RESOURCE_PACK_STACK => "ResourcePackStack",
        ids::TEXT => "Text",
        ids::START_GAME => "StartGame",
        ids::ADD_PLAYER => "AddPlayer",
        ids::ADD_ACTOR => "AddActor",
        ids::ADD_ITEM_ACTOR => "AddItemActor",
        ids::UPDATE_BLOCK => "UpdateBlock",
        ids::TILE_EVENT => "TileEvent",
        ids::ACTOR_EVENT => "ActorEvent",
        ids::MOB_EFFECT => "MobEffect",
        ids::INVENTORY_TRANSACTION => "InventoryTransaction",
        ids::PLAYER_EQUIPMENT => "PlayerEquipment",
        ids::INTERACT => "Interact",
        ids::PLAYER_ACTION => "PlayerAction",
        ids::SET_ACTOR_DATA => "SetActorData",
        ids::SET_SPAWN_POSITION => "SetSpawnPosition",
        ids::ANIMATE => "Animate",
        ids::CONTAINER_OPEN => "ContainerOpen",
        ids::INVENTORY_CONTENT => "InventoryContent",
        ids::INVENTORY_SLOT => "InventorySlot",
        ids::CRAFTING_DATA => "CraftingData",
        ids::BLOCK_ACTOR_DATA => "BlockActorData",
        ids::LEGACY_TELEMETRY_EVENT => "LegacyTelemetryEvent",
        ids::MAP_DATA => "MapData",
        ids::REQUEST_NETWORK_SETTINGS => "RequestNetworkSettings",
        ids::AVAILABLE_COMMANDS => "AvailableCommands",
        ids::COMMAND_REQUEST => "CommandRequest",
        ids::COMMAND_OUTPUT => "CommandOutput",
        ids::LEVEL_SOUND_EVENT => "LevelSoundEvent",
        ids::PLAY_SOUND => "PlaySound",
        ids::BOOK_EDIT => "BookEdit",
        ids::PACKET_VIOLATION_WARNING => "PacketViolationWarning",
        ids::BIOME_DEFINITION_LIST => "BiomeDefinitionList",
        ids::CAMERA_INSTRUCTION => "CameraInstruction",
        ids::CAMERA_AIM_ASSIST_PRESETS => "CameraAimAssistPresets",
        ids::LOCATOR_BAR => "LocatorBar",
        ids::PARTY_CHANGED => "PartyChanged",
        ids::CLIENTBOUND_ATTRIBUTE_LAYER_SYNC => "ClientboundAttributeLayerSync",
        _ => return format!("Packet#{packet_id}"),
    };
    name.to_owned()
}
